### PR TITLE
fix github-enterprise client creation

### LINKED ISSUE #352: --provider not respected "WARNING --provider not specified, assuming provider from url: github" always displayed
`argocd-autopilot app create demoapp --provider github --app github.com/argoproj-labs/argocd-autopilot/examples/demo-app/ -p myproject` 

This warning:
`WARNING --provider not specified, assuming provider from url: github`
always shows, even if `--provider github` is specified...

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: cmd/commands/app.go [hunk 1]
```diff
@@ -181,6 +181,7 @@ func RunAppCreate(ctx context.Context, opts *AppCreateOptions) error {
 		if opts.AppsCloneOpts.Auth.Password == "" {
 			opts.AppsCloneOpts.Auth.Username = opts.CloneOpts.Auth.Username
 			opts.AppsCloneOpts.Auth.Password = opts.CloneOpts.Auth.Password
+			opts.AppsCloneOpts.Provider = opts.CloneOpts.Provider
```
Comment (roi-codefresh) [inline cmd/commands/app.go:184]: I think we have an issue that this one can close, can you link it?

**Review by roi-codefresh — APPROVED** [review]
