### PR TITLE
[fix] split query param to ref|tag|sha

### LINKED ISSUE #97: App type infer fails when `--app` value references a tag
Cloning currently assumes the `?ref=<value>` is always a branch name

### LINKED ISSUE #106: getting "failed to build bootstrap manifests" since v0.2.5
since the [ref/sha/tag](https://github.com/argoproj-labs/argocd-autopilot/pull/98) change we are getting this error when running the `repo bootstrap` command:
```
FATAL failed to build bootstrap manifests: accumulating resources: accumulation err='accumulating resources from 'github.com/argoproj-labs/argocd-autopilot/manifests?tag=v0.2.5': evalsymlink failure on '/auto-pilot518561277/github.com/argoproj-labs/argocd-autopilot/manifests?tag=v0.2.5' : lstat /auto-pilot518561277/github.com: no such file or directory': evalsymlink failure on '/private/var/folders/s7/ydmj1nh917ncbk9y1mhn2dfm0000gn/T/kustomize-480526136/manifests?tag=v0.2.5' : lstat /private/var/folders/s7/ydmj1nh917ncbk9y1mhn2dfm0000gn/T/kustomize-480526136/manifests?tag=v0.2.5: no such file or directory
```

Currently I am able to get passed it by providing the `--app` flag with the correct kustomize URL, like so:
`argocd-autopilot repo bootstrap --app "github.com/argoproj-labs/argocd-autopilot/manifests?ref=v0.2.5"`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: pkg/util/repospec.go [hunk 1]
```diff
@@ -65,45 +65,25 @@ const defaultSubmodules = true
...
+	if sha != "" {
+		ref = sha
+	} else if tag != "" {
+		ref = "refs/tags/" + tag
+	} else if branch != "" {
+		ref = "refs/heads/" + branch
 	}
 
-	return parsed.Path, ref, duration, submodules
+	return parsed.Path, ref
```
Comment (roi-codefresh) [inline pkg/util/repospec.go:86]: use golang named return values

**Review by roi-codefresh — APPROVED** [review]
